//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TExp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_CostOfRepair
    {
        public int EquipmentId { get; set; }
        public decimal Price { get; set; }
    
        public virtual t_Equipment t_Equipment { get; set; }
    }
}
