//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TExp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Equipment
    {
        public t_Equipment()
        {
            this.t_Malfunction = new HashSet<t_Malfunction>();
            this.t_TypeOfEquipment = new HashSet<t_TypeOfEquipment>();
            this.t_Expertise = new HashSet<t_Expertise>();
        }
    
        public int EquipmentId { get; set; }
        public string MaterialAccount { get; set; }
        public string Name { get; set; }
        public string InventoryNumber { get; set; }
        public string SerialNumber { get; set; }
        public decimal Price { get; set; }
        public Nullable<System.DateTime> StartupDate { get; set; }
        public bool Decommission { get; set; }
        public Nullable<System.DateTime> DateOfDecommission { get; set; }
        public string MOL { get; set; }
    
        public virtual t_CostOfRepair t_CostOfRepair { get; set; }
        public virtual ICollection<t_Malfunction> t_Malfunction { get; set; }
        public virtual ICollection<t_TypeOfEquipment> t_TypeOfEquipment { get; set; }
        public virtual ICollection<t_Expertise> t_Expertise { get; set; }
    }
}
