//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TExp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Expertise
    {
        public t_Expertise()
        {
            this.t_User = new HashSet<t_User>();
            this.t_Equipment = new HashSet<t_Equipment>();
        }
    
        public int EquipmentId { get; set; }
        public string Staff { get; set; }
        public string Reason { get; set; }
        public string Conclusion { get; set; }
        public Nullable<int> NumberExp { get; set; }
        public Nullable<System.DateTimeOffset> DateExp { get; set; }
        public string Staff2 { get; set; }
        public string RequestId { get; set; }
        public Nullable<bool> IsServiceableEquipment { get; set; }
        public Nullable<bool> IsPartsSupply { get; set; }
        public Nullable<bool> IsServiceable { get; set; }
        public Nullable<bool> IsForWriteoff { get; set; }
        public Nullable<bool> IsWarrantyRepair { get; set; }
        public Nullable<bool> IsOrganizationRepair { get; set; }
        public int ExpertiseId { get; set; }
    
        public virtual ICollection<t_User> t_User { get; set; }
        public virtual ICollection<t_Equipment> t_Equipment { get; set; }
    }
}
