//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TExp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Malfunction
    {
        public t_Malfunction()
        {
            this.t_Equipment = new HashSet<t_Equipment>();
            this.t_TypeOfEquipment = new HashSet<t_TypeOfEquipment>();
        }
    
        public int FaultId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<t_Equipment> t_Equipment { get; set; }
        public virtual ICollection<t_TypeOfEquipment> t_TypeOfEquipment { get; set; }
    }
}
