//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TExp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_TypeOfEquipment
    {
        public t_TypeOfEquipment()
        {
            this.t_Equipment = new HashSet<t_Equipment>();
            this.t_Malfunction = new HashSet<t_Malfunction>();
        }
    
        public int TypeId { get; set; }
        public string Name { get; set; }
        public int Warranty { get; set; }
        public int Effective { get; set; }
        public int Limit { get; set; }
    
        public virtual ICollection<t_Equipment> t_Equipment { get; set; }
        public virtual ICollection<t_Malfunction> t_Malfunction { get; set; }
    }
}
