//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TExp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_UserRole
    {
        public t_UserRole()
        {
            this.t_User = new HashSet<t_User>();
        }
    
        public int RoleID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<t_User> t_User { get; set; }
    }
}
