//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TExp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_UsedPassword
    {
        public int UsedPasswordId { get; set; }
        public int UserId { get; set; }
        public string PasswordHash { get; set; }
    
        public virtual t_User t_User { get; set; }
    }
}
