//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TExp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TExpEntities : DbContext
    {
        public TExpEntities()
            : base("name=TExpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_Equipment> t_Equipment { get; set; }
        public virtual DbSet<t_CostOfRepair> t_CostOfRepair { get; set; }
        public virtual DbSet<t_Expertise> t_Expertise { get; set; }
        public virtual DbSet<t_Malfunction> t_Malfunction { get; set; }
        public virtual DbSet<t_Message> t_Message { get; set; }
        public virtual DbSet<t_TypeOfEquipment> t_TypeOfEquipment { get; set; }
        public virtual DbSet<t_ListForPrint> t_ListForPrint { get; set; }
        public virtual DbSet<t_User> t_User { get; set; }
        public virtual DbSet<t_UserRole> t_UserRole { get; set; }
        public virtual DbSet<t_UsedPassword> t_UsedPassword { get; set; }
    }
}
